Dragomir Robert-Simion/camera_app/blueprints/main/models.py
from datetime import datetime
from camera_app import db


class Photo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.Text, nullable=False)
    photo = db.Column(db.Text, nullable=False)

    def __repr__(self):
        return f'''Card({self.id}, "{self.description}", "{self.photo}")'''


Dragomir Robert-Simion/camera_app/blueprints/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import InputRequired

from wtforms import StringField, SubmitField
from flask_wtf.file import FileField, FileAllowed


class Form_Photo(FlaskForm):
    description = StringField('Description', validators=[InputRequired()])
    photo = FileField('Photo', validators=[FileAllowed(['jpg', 'png']), InputRequired()])

    submit = SubmitField('Add')


Dragomir Robert-Simion/camera_app/blueprints/main/routes.py
import os
from flask_login import login_required
from flask import render_template, redirect, url_for, request, flash, Blueprint, session
from sqlalchemy import exc
from camera_app import db

from camera_app.blueprints.main.forms import Form_Photo
from camera_app.blueprints.main.models import Photo

main = Blueprint('main', __name__, template_folder='templates', static_folder='static', static_url_path='/static')


def iterate_pages(table):
    return table.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=2)


def upload_photo(form_file):
    if type(form_file) == str:
        name = form_file
    else:
        name = form_file.filename
    file_path = os.path.join(main.root_path, 'static', name)
    form_file.save(file_path)
    return name


@main.route("/edit_photo/<int:id>", methods=['GET', 'POST'])
@main.route('/add_photo', methods=['GET', 'POST'])
@login_required
def add_photo(id=None):
    form = Form_Photo()

    if id is not None: photo = Photo.query.get_or_404(id)

    if request.method == 'GET':
        form.process(request.args)
        if id is not None:
            form.description.data = photo.description
            form.photo.data = photo.photo

    if form.validate_on_submit():
        try:
            if id is not None:
                photo.description = form.description.data
                photo.photo = upload_photo(form.photo.data)

                db.session.commit()

                flash('Success!', 'success')
                return redirect(url_for('main.photo', id=photo.id))
            else:
                row = Photo(description=form.description.data, photo=upload_photo(form.photo.data))
                db.session.add(row)
                db.session.commit()

                return redirect(url_for('main.photos'))
                flash('Success!', 'success')
        except exc.IntegrityError as e:
            flash(f'Error: {e}', 'danger')

    return render_template('add_photo.html', title='Add a photo', form=form)


@main.route("/photo/<int:id>")
@login_required
def photo(id):
    session['photo'] = id
    return render_template('photo.html', photo=Photo.query.get_or_404(id))


@main.route("/delete_photo/<int:id>")
@login_required
def delete_photo(id):
    db.session.delete(Photo.query.get_or_404(id))
    db.session.commit()
    return redirect(url_for('main.photos'))


@main.route('/', methods=['GET', 'POST'])
@main.route("/photos")
@login_required
def photos():
    page = request.args.get('page', 1, type=int)
    return render_template('photos.html', title='Photos', photos=Photo.query.paginate(per_page=5, page=page))

Dragomir Robert-Simion/camera_app/blueprints/main/templates/add_photo.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-4"></div>

    <div class="content-section col-md-4">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom md-4">{{ title }}</legend>

            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
				{{ form.photo.label() }}
				{{ form.photo(class="form-control-file") }}
				{% for error in form.photo.errors %}
					<span class="text-danger">{{ error }}</span><br>
				{% endfor %}
            </div>
        </fieldset>

        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>

    <div class="col-md-4"></div>
</div>
{% endblock content %}

Dragomir Robert-Simion/camera_app/blueprints/main/templates/photo.html
{% extends "layout.html" %}
{% block content %}
	<img src="{{ url_for('main.static', filename=photo.photo) }}" alt="{{ photo.description }}">
	<p>{{ photo.description }}</p>
	<hr>

	<a class="btn btn-outline-info" href="{{ url_for('main.photos') }}">Go back</a>
	<a class="btn btn-info" href="{{ url_for('main.add_photo', id=photo.id) }}">Change</a>
	<a class="btn btn-danger" href="{{ url_for('main.delete_photo', id=photo.id) }}">Delete</a>
{% endblock content %}

Dragomir Robert-Simion/camera_app/blueprints/main/templates/photos.html
{% extends "layout.html" %}
{% block content %}
	{% for photo in photos.items %}
		<a href="{{ url_for('main.photo', id=photo.id) }}">
			<img src="{{ url_for('main.static', filename=photo.photo) }}" alt="{{ photo.description }}">
		</a>
		<hr>
	{% endfor %}
    <br>

    {% for page in pages %}
        {% if page %}
            {% if photos.page == page %}
                <a href="{{ url_for('main.photo', page=page) }}" class="btn btn-info md-1">{{ page }}</a>
            {% else %}
                <a href="{{ url_for('main.photo', page=page) }}" class="btn btn-outline-info md-1">{{ page }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
	<a class="btn btn-success" href="{{ url_for('main.add_photo') }}">Add Photo</a>
{% endblock content %}